### ISSUE TITLE
Error message in Karaf console on Windows 10 

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-distro#530]
Since switching to Karaf 4.1.2 the following message appears on the Karaf console:

```
Error in initialization script: E:\openhab-2.2.0-SNAPSHOT\userdata\openhab-2.2.0-SNAPSHOTuserdataetc\shell.init.script: E:\openhab-2.2.0-SNAPSHOT\userdata\openhab-2.2.0-SNAPSHOTuserdataetc\shell.init.script
```
I have downloaded Karaf 4.1.2. and it does not show any error messages. I suppose it has something to do with the files used to start up openHAB.

**Comment by hr3** [comment]
I have the same problem, at least with #1031to #1033.

**Comment by martinvw** [comment]
I have / had it to, it is in a piece about setting up color output.

Does your environment run fine for the rest?

**Comment by hr3** [comment]
I have some problem, but I think, it has other resons.

**Comment by martinvw** [comment]
In my case it also was not the reason to stop it from starting that was:  https://github.com/openhab/openhab-docker/issues/102

**Comment by s4ndst0rm** [comment]
Same issue here with build 1037. 
In addition to that error message my logging is complete wrong.
There is no event.log and my openhab.log is under the root dir of the volume. So both logfiles are not located in userdata/logs.

**Comment by gfischershaw** [comment]
Others reported it starting after build 1003 and on or before 1010.

So is something now calling convertPaths twice?

**Comment by martinvw** [comment]
> Others reported it starting after build 1003 and on or before 1010.

https://community.openhab.org/t/karaf-upgrade/33208

**Comment by Celaeno1** [comment]
I updated from build 982 to build 1039. Having the same error!

**Comment by Celaeno1** [comment]
I “solved” the problem! I commented the following line in userdata\etc\system.properties:

# karaf.shell.init.script = ${karaf.etc}/shell.init.script
Now, the error is gone!

Can anyone confirm this, too?

**Comment by NurNano** [comment]
Yea I can confirm this. Now it starts! But still creates a directory one directory abovoe the .bat. Named "OPENHA~2.0-B" at my system.

**Comment by gfischershaw** [comment]
Except that shell.init.script is likely never run since it is not defined.
Everything looks OK on the way in within karaf.bat, so I presume it must be the new version of karaf itself that was checked in on 1009.

**Comment by Celaeno1** [comment]
I tested also with this in userdata\etc\system.properties:

    karaf.shell.init.script = c:/Openhab2/userdata/etc/shell.init.script

The error also is gone! But now I would like to know how to test it!

Anyone else who knows that?

**Comment by Celaeno1** [comment]
Further tests with:

\userdata\etc\system.properties:

    karaf.shell.init.script = ${karaf.base}/etc/shell.init.script

result: --> C:\Openhab2\userdata\Openhab2userdata\etc\shell.init.script

    karaf.shell.init.script = ${karaf.home}/etc/shell.init.script

result: --> C:\Openhab2\userdata\Openhab2runtime\etc\shell.init.script

It seems that at all variables are missing the  \ or /  in the path:

karaf.base = Openhab2userdata
karaf.home = Openhab2runtime
karaf.etc = Openhab2userdataetc

Then I forced an exception:

     Exception in thread "Karaf local console user openhab" java.nio.file.InvalidPathException: Illegal char 
    <:> at index 2: $C:Openhab2userdataetc/shell.init.script
            at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
            at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
            at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
            at sun.nio.fs.WindowsPath.parse(Unknown Source)
            at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
            at sun.nio.fs.AbstractPath.resolve(Unknown Source)
            at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
            at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
            at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
            at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
            at 
    org.apache.karaf.shell.impl.console.ConsoleSessionImpl.executeScript(ConsoleSessionImpl.java:490)
           at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:342)
           at java.lang.Thread.run(Unknown Source)


Maybe someone else knows where and what to do, now??

**Comment by MHerbst** [comment]
I have compared the batch files and the system.properties file delivered with openHAB with the files delivered with plain Karaf.

And finally I found this comment in the system.properties file delivered with Karaf
```
#
# Location of a shell script that will be run when starting a shell
# session.  This script can be used to create aliases and define
# additional commands.
# Do not use absolute paths to avoid problems on windows.
#
karaf.shell.init.script = etc/shell.init.script,etc/scripts/*.script
```

After changing openHAB's system.properties file as follows:
```
karaf.shell.init.script = etc/shell.init.script,etc/scripts/*.script
````
the error message disappeared!

It seems that everything works correctly with this change, but I am not sure whether it is also OK for Linux environments and therefore it will need some further testing.

@kaikreuzer Do you have any idea why this setting was modified for openHAB and changed to an absolute path?

**Comment by kaikreuzer** [comment]
@MHerbst I assume I didn't read the comment carefully enough and must have changed it to an absolute path. The issue is that we have [different locations of the etc folder for the different installation types](http://docs.openhab.org/installation/linux.html#file-locations). I am actually not 100% certain, where the "." location is for an apt-based installation (@BClark09 can you tell?). If it is the "openHAB application", we might have a chance to move these scripts to runtime/etc, which should be the same for all installation types; might be worth a try.

**Comment by BClark09** [comment]
Editing `system.properties` to contain the following should be enough:

```
karaf.shell.init.script = etc/shell.init.script
```

To test, I added the following line to `$OPENHAB_USERDATA/etc/shell.init.script`

```
bentest = { help $args } ; 
```
![image](https://user-images.githubusercontent.com/8983584/30587570-8e90b880-9d2b-11e7-8381-3f0d9480594f.png)

So it looks like the working directory is $OPENHAB_USERDATA, just as it is in @MHerbst's instance.

**Comment by kaikreuzer** [comment]
Thanks, the fix should then pretty simple indeed.
Actually I had hoped we could move the stuff to runtime in order to keep userdata clean, but it seems that there isn't a simple way to reference this folder then :-(

**Comment by kaikreuzer** [comment]
@MHerbst I just noticed that the line
```
# Do not use absolute paths to avoid problems on windows.
```
Isn't contained in our system.properties, so that is why I didn't notice that. Browsing the Karaf code, I now just [found this from 8 days ago](https://github.com/apache/karaf/commit/dcffc68595e465f50e809919a2044648436c027e) 😲 - so before removing that prefix, I would want to clarify what this is about on https://issues.apache.org/jira/browse/KARAF-5352.

**Comment by jbonofre** [comment]
The value looks good to me. It seems that the problem is that `karaf.etc = Openhab2userdataetc` (the `/` is missing).

**Comment by BClark09** [comment]
The underlying cause for that problem is a mystery to me however. It is set properly in [oh2_dir_layout.sh](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/oh2_dir_layout.bat#L33):
```
set KARAF_ETC=%OPENHAB_USERDATA%\etc
```
which gets passed to karaf.etc in [karaf.bat](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/karaf.bat#L389):
```
-Dkaraf.etc="%KARAF_ETC%" ^
```

**Comment by MHerbst** [comment]
@jbonofre Too me it seems that the "/" or "\" is removed somewhere within Karaf itself if the entry contains a reference to an environment variable. 
I have modified the batch file that starts Karaf and printed all environment before Karaf is started. All environment variables (KARAF_HOME, KARAF_ETC, KARAF_BASE) had correct values. 
As you can see in this post https://github.com/openhab/openhab-distro/issues/530#issuecomment-330114790, it works if `{$karaf.etc} is replaced by a fully qualified path.`

Maybe the cause lies in the code that resolves the variables.

**Comment by kaikreuzer** [comment]
@MHerbst Could you test that on a plain Karaf installation and if there are problems when setting KARAF_ETC manually, would you add a comment to https://issues.apache.org/jira/browse/KARAF-5352? To me it yet isn't clear where the path gets set and where the backslash is lost on the way.

I also wonder whether it needs to be forward or back slashes on Windows, at the moment we seem to have an unhealthy mix...

**Comment by hr3** [comment]
I put the echos behind
381 if "%IS_RUNNABLE%" == "true" (
and get this on Windows10Pro(32Bit) 1703 15063.608
```
Launching the openHAB runtime...
WARNING: Running Karaf on a Java HotSpot Client VM because server-mode is not available.
Install Java Developer Kit to fix this.
For more details see http://java.sun.com/products/hotspot/whitepaper.html#client
.
JAVA:C:\Program Files\Java\jre1.8.0_144\bin\java
JAVA_OPTS:   -Dopenhab.home=C:\openHAB\OPENHA~1.0-S   -Dopenhab.conf=C:\openHAB\OPENHA~1.0-S\conf   -Dopenhab.runtime=C:\openHAB\OPENHA~1.0-S\runtime   -Dopenhab.userdata=C:\openHAB\OPENHA~1.0-S\userdata   -Dopenhab.logdir=C:\openHAB\OPENHA~1.0-S\userdata\logs   -Dfelix.cm.dir=C:\openHAB\OPENHA~1.0-S\userdata\config   -Djetty.host=0.0.0.0   -Dorg.ops4j.pax.web.listening.addresses=0.0.0.0   -Dorg.osgi.service.http.port=8080   -Dorg.osgi.service.http.port.secure=8443 -XX:+UseG1GC   -Djava.awt.headless=true
JAVA_HOME:C:\Program Files\Java\jre1.8.0_144
OPTS:-Dkaraf.startLocalConsole=true -Dkaraf.startRemoteShell=true
CLASSPATH:C:\openHAB\OPENHA~1.0-S\userdata\conf;C:\openHAB\openhab-2.2.0-SS1055\runtime\bin\..\lib\boot\org.apache.karaf.diagnostic.boot-4.1.2.jar;C:\openHAB\openhab-2.2.0-SS1055\runtime\bin\..\lib\boot\org.apache.karaf.jaas.boot-4.1.2.jar;C:\openHAB\openhab-2.2.0-SS1055\runtime\bin\..\lib\boot\org.apache.karaf.main-4.1.2.jar;C:\openHAB\openhab-2.2.0-SS1055\runtime\bin\..\lib\boot\org.osgi.core-6.0.0.jar
OPENHAB_USERDATA:C:\openHAB\OPENHA~1.0-S\userdata
OPENHAB_LOGDIR:C:\openHAB\OPENHA~1.0-S\userdata\logs
KARAF_HOME:C:\openHAB\openhab-2.2.0-SS1055\runtime\bin\..
KARAF_BASE:C:\openHAB\OPENHA~1.0-S\userdata
KARAF_ETC:C:\openHAB\OPENHA~1.0-S\userdata\etc
KARAF_DATA:C:\openHAB\OPENHA~1.0-S\userdata
KARAF_OPTS:
MAIN:org.apache.karaf.main.Main
ARGS:

                          __  _____    ____
  ____  ____  ___  ____  / / / /   |  / __ )
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  |
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/
    /_/                        2.2.0-SNAPSHOT
                               Build #1055

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

Error in initialization script: C:\openHAB\openhab-2.2.0-SS1055\userdata\openHABopenhab-2.2.0-SS1055userdataetc\shell.init.script: C:\openHAB\openhab-2.2.0-SS1055\userdata\openHABopenhab-2.2.0-SS1055userdataetc\shell.init.script
openhab>
```

**Comment by hr3** [comment]
I modyfied system.properties and deocument the results
```
#karaf.shell.init.script = ${karaf.etc}/shell.init.script		#C:\oh22\userdata\oh22userdataetc\shell.init.script
#karaf.shell.init.script = ${karaf.etc}\shell.init.script		#C:\oh22\userdata\oh22userdataetcshell.init.script
#karaf.shell.init.script = ${karaf.etc}				#C:\oh22\userdata\oh22userdataetc
#karaf.shell.init.script = C:\oh22\userdata\etc\shell.init.script	#C:\oh22\userdata\oh22userdataetcshell.init.script
#karaf.shell.init.script = C:/oh22/userdata/etc/shell.init.script	#works
#karaf.shell.init.script = etc/shell.init.script			#works
  karaf.shell.init.script = shell.init.script				#C:\oh22\userdata\shell.init.script
```

**Comment by BClark09** [comment]
So, in otherwords ${karaf.etc} is fine until the point in which it's processed by the Java process, where it gets muddled by backslashes?

**Comment by MHerbst** [comment]
@kaikreuzer I have performed some tests and added the results to the Apache jira. It doesn't matter how KARAF_ETC is set. The Java code of Karaf seems to perform some conversion while expanding karaf.etc and this conversion probably does not work correctly on Windows 10. It seems that all directory names a translated to the system's standard separator character. Therefore it makes no difference whether you use forward or back slashes.

> I also wonder whether it needs to be forward or back slashes on Windows, at the moment we seem to have an unhealthy mix...
This is really a problem. Generally, Windows supports forward and back slashes and you can even mix different slashes in a path. In Java code (and properties files) I normally use forward slashed in order to avoid escaping of the back slashes. 
But if some Java code e.g. tries to figure out whether a path contains a (back) slash at the end this may fail if the code only checks for operating system's standard separator (value of system property "file.separator").

**Comment by kaikreuzer** [comment]
Many thanks for your analysis and for reporting details at the Karaf issue tracker. Let's see if the issue can be confirmed and fixed there!

**Comment by matushromada** [comment]
Hi, it seems that the issue was resolved in Karaf issue tracker. But the error still appears on the latest OH snapshot.

**Comment by martinvw** [comment]
Please note that the version in which it is fixed is not released so we have to wait for that: https://issues.apache.org/jira/projects/KARAF/versions/12341130

**Comment by matushromada** [comment]
Thanks for explanation!

**Comment by matushromada** [comment]
I was again looking on releases of Karaf and all versions are marked as unreleased and also newer version available. Looks that they aren’t marking them here as released? https://issues.apache.org/jira/projects/KARAF?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page

**Comment by kaikreuzer** [comment]
You can find their release schedule at http://karaf.apache.org/download.html.

**Comment by MP91** [comment]
This issue should be fixed in Karaf 4.1.3 which was released on 10/31. The newest snapshot of OpenHab from 11/04 still shows the same error.
Is there any timeschedule about the snapshot-releases or when the new version of Karaf will be included?

**Comment by martinvw** [comment]
Creating a pull request to update the version in the [pom.xml](https://github.com/openhab/openhab-distro/blob/master/pom.xml#L59) is easy, but it should of course be tested it as well.

**Comment by matushromada** [comment]
The error still seems to be present in the build #1078 from 11/11

**Comment by kaikreuzer** [comment]
Certainly so, as it is still using Karaf 4.1.2.

**Comment by kaikreuzer** [comment]
https://github.com/openhab/openhab-distro/pull/570 is merged, so please check whether the issue is solved in distro 1083 and above!

**Comment by BClark09** [comment]
Alas:

![image](https://user-images.githubusercontent.com/8983584/32986157-5e69118a-ccc3-11e7-89a4-19c6c31b17fc.png)

**Comment by kaikreuzer** [comment]
No good. This init script is a pain, even on my Mac it now fails on the first startup.
Does anyone happen to know in which file the Karaf fix is contained? Is it something that we manually need to sync to the openHAB distro? I have taken shell.init.script from Karaf 4.1.3, so this should be up to date.

**Comment by martinvw** [comment]
Afaik the problem originates from around: 

https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/userdata/etc/shell.init.script#L50

It seems that they commented out line 53 but that makes the vars unused, so maybe we should just remove the whole block.

However I fear that we have bigger problems :-( 

https://community.openhab.org/t/jetty-update-karaf-4-1-3-upgrade-and-full-lsp-support/36354/12

And my own test with the docker upgrade is also not looking good, note that I have version 1084 instead of 1083.

**Comment by kaikreuzer** [comment]
Could you test if you find some changes to shell.init.script that make it work better (maybe also without causing having to start twice, which might help for the docker setup)?

**Comment by matushromada** [comment]
Trying to answer Kai's question about which file the fix is contained: It seems that is system.properties as seen [here](https://github.com/apache/karaf/pull/356/files).

**Comment by martinvw** [comment]
Thanksgiving, but imho this looks pretty okay already:

https://github.com/openhab/openhab-distro/blob/b1c1118ceedbef09b3e460fc68d721f828fbe65c/distributions/openhab/src/main/resources/userdata/etc/system.properties#L31

**Comment by MP91** [comment]
I´m still getting the same error on windows with snapshot 1084...

**Comment by matushromada** [comment]
I've noticed [here (Fix startup scripts on windows](https://github.com/jbonofre/karaf/commits/dcffc68595e465f50e809919a2044648436c027e/assemblies/features/base/src/main/resources/resources/etc/system.properties), that issue with shell.init.script on windows was resolved in karaf by using "etc/shell.init.script" in system.properties Not sure if I'm helpful or bringing just noise - just tell me.

**Comment by MP91** [comment]
It seems to work with just karaf.shell.init.script = shell.init.script. So without any further paths. But I will investigate the behavior further

**Comment by martinvw** [comment]
> It seems to work with just karaf.shell.init.script = shell.init.script. So without any further paths. But I will investigate the behavior further

Maybe a stupid question but isn't that maybe caused by the fact that it cannot find the file and no error will happen. Because the actual error is in the file itself AFAIK.

**Comment by MP91** [comment]
Yes, that was the point. The path to the script was wrong. With ${karaf.etc} it was still the path where the backslashes were missing.
But unfortunately it is still not working. The error is everytime: "command not found"...

**Comment by martinvw** [comment]
Sorry, I'm having another problem on my machines they complain about an error in the actual script, that is on Mac OS and Linux.

**Comment by BClark09** [comment]
To take a step back a bit, before Karaf 4.1.2 the line in question was:

```
 karaf.shell.init.script = etc/shell.init.script 
```

This uses a relative path which is safely parsed through Java for Windows. 

The line now contains:

```
 karaf.shell.init.script = ${karaf.etc}/shell.init.script 
```

Which evaluates to a full path and gets garbled by the process. The fix, that is not currently in openHAB's implementation is this one:

https://github.com/apache/karaf/commit/066d28aa455d896ac6269c0b0efca67cda90c716

To resolve this issue we need to at least set this to a relative path (i.e. `etc/shell.init.script`)  OR pull in this patch.

**Comment by martinvw** [comment]
So that is actually in karaf-4.2.0.M1? At least according to github. Please try it would be great if that finally solves it :-)

**Comment by BClark09** [comment]
It'll work in both versions:

|Version|FileStream.java contains...|system.properties should contain...|
|:-|:-|:-|
|Karaf 4.1.3|`Path cur = Paths.get(System.getProperty("karaf.base"));`| `karaf.shell.init.script = etc/shell.init.script`|
|Karaf 4.2.0.M1|`Path cur = Paths.get(System.getProperty("karaf.etc"));`| `karaf.shell.init.script = shell.init.script`|

**Comment by BClark09** [comment]
After downloading 4.1.3, system.properties contains the fix also.

**Comment by BClark09** [comment]
@martinvw, @kaikreuzer, would the distro contain the default system.properties if we simply remove it from this repository? If so, then the appropriate fix should be:

1. Delete [system.propeties](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/userdata/etc/system.properties)
2. Add custom.system.properties with the following information:

```
karaf.local.user = openhab
mdnsName=openhab
smarthome.servicepid=org.openhab
smarthome.servicecfg=${openhab.runtime}/services.cfg
smarthome.userdata=${openhab.userdata}
smarthome.configdir=${openhab.conf}
org.quartz.properties=${openhab.runtime}/etc/quartz.properties
jetty.keystore.path=${openhab.userdata}/etc/keystore
jetty.truststore.path=${openhab.userdata}/etc/keystore
equinox.ds.block_timeout=240000
equinox.scr.waitTimeOnBlock=60000
```

**Comment by martinvw** [comment]
Sounds hopeful, I hope @kaikreuzer can give a detailed opinion

**Comment by kaikreuzer** [comment]
> Add custom.system.properties which also resolves this todo

I do not understand why this should work. The todo references https://issues.apache.org/jira/browse/KARAF-3949 which is still unresolved.

So the correct fix would instead be to keep the existing system.properties and only update all the "standard" settings to be identical to what is shipped in Karaf 4.1.3.

**Comment by BClark09** [comment]
The first line of Karaf's system properties in 4.1.3 is:

```
${optionals} = custom.system.properties
```

Anything written in the referenced file overwrites the standard system.properties.

**Comment by kaikreuzer** [comment]
Interesting :-)
So it might be worth to tell this to the Karaf people on their issue tracker!

So if this works - please create an according PR!

**Comment by BClark09** [comment]
Will do, the screenshot of the working instnce I added above uses the custom file so all should be fine.

**Comment by BClark09** [comment]
Done :-)

**Comment by hr3** [comment]
#1090 doesn't start
```
2017-11-23 08:53:27.050 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifact org.jline:jline:jar:3.5.0: [Could not find artifact org.jline:jline:jar:3.5.0 in openhab (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.2/)]
java.io.IOException: Error resolving artifact org.jline:jline:jar:3.5.0: [Could not find artifact org.jline:jline:jar:3.5.0 in openhab (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.2/)]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720) [4:org.ops4j.pax.url.mvn:2.5.3]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659) [4:org.ops4j.pax.url.mvn:2.5.3]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600) [4:org.ops4j.pax.url.mvn:2.5.3]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567) [4:org.ops4j.pax.url.mvn:2.5.3]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:47) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60) [9:org.apache.karaf.features.core:4.1.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
	Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jline:jline:jar:3.5.0 in openhab (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.2/)
		at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223) [4:org.ops4j.pax.url.mvn:2.5.3]
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294) [4:org.ops4j.pax.url.mvn:2.5.3]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705) [4:org.ops4j.pax.url.mvn:2.5.3]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659) [4:org.ops4j.pax.url.mvn:2.5.3]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600) [4:org.ops4j.pax.url.mvn:2.5.3]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567) [4:org.ops4j.pax.url.mvn:2.5.3]
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:47) [9:org.apache.karaf.features.core:4.1.3]
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60) [9:org.apache.karaf.features.core:4.1.3]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
		at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.jline:jline:jar:3.5.0
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) ~[?:?]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) ~[?:?]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223) ~[?:?]
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705) ~[?:?]
	... 12 more
2017-11-23 08:53:27.066 [ERROR] [ternal.service.BootFeaturesInstaller] - Error installing boot features
org.apache.karaf.features.internal.util.MultiException: Error:
	Error downloading mvn:org.jline/jline/3.5.0
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:84) ~[?:?]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72) ~[?:?]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:375) ~[?:?]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:372) ~[?:?]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:187) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:291) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:287) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1248) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$1(FeaturesServiceImpl.java:1147) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
	Suppressed: java.io.IOException: Error downloading mvn:org.jline/jline/3.5.0
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77) [9:org.apache.karaf.features.core:4.1.3]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
		at java.lang.Thread.run(Thread.java:748) [?:?]
	Caused by: java.io.IOException: Error resolving artifact org.jline:jline:jar:3.5.0: [Could not find artifact org.jline:jline:jar:3.5.0 in openhab (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.2/)]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:47) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60) ~[?:?]
		... 7 more
		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jline:jline:jar:3.5.0 in openhab (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.2/)
			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223) [4:org.ops4j.pax.url.mvn:2.5.3]
			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294) [4:org.ops4j.pax.url.mvn:2.5.3]
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705) [4:org.ops4j.pax.url.mvn:2.5.3]
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659) [4:org.ops4j.pax.url.mvn:2.5.3]
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600) [4:org.ops4j.pax.url.mvn:2.5.3]
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567) [4:org.ops4j.pax.url.mvn:2.5.3]
			at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:47) [9:org.apache.karaf.features.core:4.1.3]
			at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60) [9:org.apache.karaf.features.core:4.1.3]
			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
			at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
			at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
			at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
			at java.lang.Thread.run(Thread.java:748) [?:?]
	Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.jline:jline:jar:3.5.0
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) ~[?:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) ~[?:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223) ~[?:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600) ~[?:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:47) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60) ~[?:?]
		... 7 more
```

**Comment by matushromada** [comment]
Using [documentation for updating on Windows](http://docs.openhab.org/installation/windows.html) the error persists. Should I propose to add a file for deletion - system.properties - during the update process?

**Comment by BClark09** [comment]
Good spot! The list in the [Updating the openHAB Runtime](http://docs.openhab.org/installation/windows.html#updating-the-openhab-runtime) section should include both:

```
userdata\etc\system.properties
userdata\etc\custom.system.properties
```

**Comment by matushromada** [comment]
Done [#575](https://github.com/openhab/openhab-docs/pull/575)
