### ISSUE TITLE
IDE Setup problem when trying to download plugins for target definition.

### ISSUE THREAD

**Issue by Shibonja** [openhab/openhab-distro#71]
Hi

Great work releasing openHab2 beta, congratulations. 

Today I followed the IDE setup, but I am getting an popup that ask's bintray username and password. When trying to reload target platform I am getting the same  username and password popup again, but without entering the credentials I can't download all needed plugins.

Am i missing something in my setup?

Regards, shibonja.

**Comment by kaikreuzer** [comment]
Please pull the latest master of openhab-distro - unfortunately, I broke the target platform, but fixed it with this PR 10 minutes later again: https://github.com/openhab/openhab-distro/pull/70
Please re-open this issue in case it does not solve your problem, thanks!

**Comment by Shibonja** [comment]
Hi @kaikreuzer 

Is the target platform broken again. This time I can not load repositories from: https://github.com/openhab/openhab.repo/raw/master/jetty-deps

Regards, Haris.

**Comment by dvanherbergen** [comment]
Pulling the latest version should fix that.

**Comment by Shibonja** [comment]
Hi @dvanherbergen 

I just made the pull request and again still the same issue.

**Comment by dvanherbergen** [comment]
Did you pull the latest version of all the repos that you are using (openhab, openhab2-addons, openhab-distro)?

**Comment by Shibonja** [comment]
I am using only openhab-distro. I have no other repos.

**Comment by dvanherbergen** [comment]
Did you try ```mvn clean install -U```? Can you post the error that you are getting?

**Comment by Shibonja** [comment]
mvn clean install -U is running, in the meantime, here is my error in Eclipse:

http://oi64.tinypic.com/1zh31ci.jpg

**Comment by dvanherbergen** [comment]
Sorry, I misunderstood the error. I assumed you were having an issue with the maven build.
It appears that there is indeed still the old repository in there. It is no longer needed and can be removed. I will raise a PR for this.

**Comment by kaikreuzer** [comment]
Sorry @dvanherbergen that I deleted the openhab.repo accidentially and caused all these problems through that. I have just brought the repo back up again, so that the old target platform should continue to work for the time being.

**Comment by dvanherbergen** [comment]
Thanks! Then we can leave the target update for another day :-)

**Comment by kaikreuzer** [comment]
Yep. Luckily I still had a local copy ;-)

**Comment by Shibonja** [comment]
Thanks for quick support and help.
